bitcraze/crazyflie2-nrf-firmware

interface/esb.h
interface/syslink.h
src/esb.c
src/main.c

This commit adds support for sending RSSI measurements from the radio to
the main processor, STM32. This is done by storing the RSSI measurements
done on each received packet and then forwarding that RSSI sample to the
main processor at certain intervals. Currently the interval is set up to
perform at 100Hz.
This commit adds a new log constant used to send RSSI samples. A quick
updated of esb.h so that RSSI samples are not converted
between uint32_t -> int -> uint32_t.
Note: This commit is intended to work with the RSSI pull request to crazyflie-firmware

Added support for sending RSSI from radio to STM32

---

interface/esb.h
interface/syslink.h
src/esb.c
src/main.c

This is part 2 of the effort of improving the multi-flie support by allowing custom device addresses.
Please see https://github.com/bitcraze/crazyflie-clients-python/pull/161 for the matching UI changes.

Add option to set device address of the Crazyflie via syslink interface.

---

src/main.c

The following commands are added: AllOff (full power-off), SysOff (STM32 off), SysOn (STM32 on), GetVBat (check battery status without turning STM32 on).
We use those commands within the Crazyswarm project to put all CFs in power-saving mode while they are not in use, and to perform fast battery checks to identify CFs which need a new battery. So far, the commands are supported within the crazyflie_tools of the crazyflie_ros package.
With this change, the Crazyswarm can operate on the latest official radio and nrf51 firmwares:-)
Is there any wiki page where those commands should be documented?

Add additional bootloader commands.

---

src/esb.c

Adding battery voltage to the ESB ACK packet. This is useful for
lightweight logging in DeviationTx and while running
Betaflight/Cleanflight (where CRTP logging is unavailable)
This is defaulting to disabled because it increases ACK overhead
slightly. To enable, compile with RSSI_ACK_PACKET undefined and
RSSI_VBAT_ACK_PACKET defined (see the Makefile)

Adding VBat to NRF ESB ACK (disabled by default)

---

src/main.c

This fixes an issue where bootloader commands could only be sent
after the safelink was disabled.

Handle bootloader commands if safelink is enabled

---

Makefile
interface/debug.h
src/debug.c
src/lib/Segger_RTT/License.txt
src/lib/Segger_RTT/README.txt
src/lib/Segger_RTT/RTT/SEGGER_RTT.c
src/lib/Segger_RTT/RTT/SEGGER_RTT.h
src/lib/Segger_RTT/RTT/SEGGER_RTT_ASM_ARMv7M.S
src/lib/Segger_RTT/RTT/SEGGER_RTT_Conf.h
src/lib/Segger_RTT/RTT/SEGGER_RTT_printf.c
src/lib/Segger_RTT/Syscalls/SEGGER_RTT_Syscalls_GCC.c
src/lib/Segger_RTT/Syscalls/SEGGER_RTT_Syscalls_IAR.c
src/lib/Segger_RTT/Syscalls/SEGGER_RTT_Syscalls_KEIL.c
src/lib/Segger_RTT/Syscalls/SEGGER_RTT_Syscalls_SES.c
src/main.c

Segger Real Time Transfer (RTT) is a high-speed protocol that can
be used with JLink debug probes. It allows to exchange data very
fast by using shared memory and SWO. It can be used for debugging
(printing inside interrupt routines works fine).
Tested with JLink EDU Mini and CF2.0.

Add support for DEBUG_PRINT using SEGGER RTT

---

src/esb.c

BOOTLOADER_CMD_RESET_INIT and BOOTLOADER_CMD_GETVBAT actually return
packets, but clients cannot receive the data because empty ack's are
returned.
Fixes https://github.com/USC-ACTLab/crazyswarm/issues/174 and
https://github.com/whoenig/crazyflie_cpp/issues/10.

Acknowledge bootloader cmds with regular ack rather than empty ack.

---

readme.md

If `make CLOAD` is used, make will not find the `cload` target.

Change make CLOAD to make cload in readme.md

---

Makefile
src/pm.c

* Fix compiler warning caused by a missing semicolon.
* Enable error on warnings, so that future the CI finds such issues in
the future.

Fix compiler warning introduced in 76fe2ce

---

src/esb.c

Now that we are using Safelink to prevent packet loss and packet duplication, the Nordic's ESB Packet ID is not useful anymore and could actually cause packet loss.
This change disable the packet id handling and the logic that was droppin packet if packet ID and CRC are the same as the previous packet.

Disable check for ESB pid

---

src/pm.c

When updating the Lighthouse deck as part of the flashing procedure we
sometiems get stuck. The Lighthouse deck does not power on.
We suspect this is connected to the capacitors on the deck not getting
enough time to discharge in some conditions on some boards.
Some users tried out firmware with 250 ms and 300 ms delays and the 300
ms delay fixed the issue for them. We increase the delay here to 350 ms
to err on side of caution.
If boot-up times becomes an issue we could change this to only take
effect on soft-resets.
Fixes: #56

pm: Increase delay before powering system

---

Makefile
interface/syslink.h
src/main.c
tools/build/generateVersionHeader.py

- Generate version.h with build versions
- Add SYSLINK_SYS_NRF_VERSION message

Add version handling

---

src/main.c

Fix crash when using P2P TX only communication.
Fixes #62

Disable BLE when TX P2P communication

---

interface/pinout.h

Matches updated (corrected) deck multiplexing schematic.
Related to bitcraze/crazyflie2-nrf-firmware#66

Add N_IO_1, N_IO_2 defines

---

interface/syslink.h
src/main.c
src/syslink.c

The nrf is sending battery information continuously after a delay after startup. This mechanism was broken causing it to never send the battery information. The logic has now been rewritten so that the syslink packets going out will fist be allowed to do so after a packet has been received which happes as soon as the STM sets that radio address.
Some minor refactoring as well splitting the big mainLoop function into sub-functions.
Fixes #1043

Syslink will now only enable send after a packet has been received.

---

interface/syslink.h
interface/uart.h
src/main.c
src/uart.c

Add code to collect debug data for the bitcraze/crazyflie-firmware#998
Added new syslink message to send the data to the STM on request.
We do not know what is causing this problem and this is a first step to collect data. This code should probably be removed when the problem is solved.

Add debug probe for radio setup

---

interface/syslink.h
interface/uart.h
src/main.c
src/syslink.c
src/uart.c

Debug code to figure out problems with the syslink

Added more syslink debug probes

---

Makefile
src/esb.c
src/ow/owlnk.c
src/systick.c
src/uart.c

The nRF51822 code has not been optimized by the compiler. During investigation of the syslink this was found and optimizing it improves the syslink speed and less uart-RTS delays. In overall it should improve performance.
When first enabling optimization the nRF locked up. This turned out to be the running variable in OwLnk.c not being volatile and altered in TIMER1_IRQHandler. This solved the lockup but to be sure I made all variables used in interrupt service routines volatile.

Optimized build from none (-O0) to size (-Os)

---

Makefile
src/esb.c

There seems to be a problem when running with the optimized compile. One of the load tests in the stab lab (`test_bandwidth_big_packets()`) indicates that we loose some packets.
We have not figured out what the reason is, and at this point we prioritize getting a stable release out. This PR reverts the compiler optimization.
Related to #72

Revert optimization

---

.github/workflows/CI.yml
.github/workflows/read_build_targets.yml
.github/workflows/release.yml
build_targets.json
module.json

This PR introduces a new file (build_targets.json) with a list of platforms to build. This file is used both in CI and release builds.

Read build targets from file

---

interface/pm.h
src/main.c
src/pm.c

Changed the flags that are sent through syslink from nrf to stm to make more sense. Previously, the value `pGood` was included, which had different physical meanings depending on platform (bolt, CF2).
I also added some explanation in the code, as comments.

Changed power bit flags sent through syslink

---

src/main.c

See https://github.com/IMRCLab/crazyswarm2/issues/327 for background
After the changes in #91 there is a difference when BLE is disabled (after the first CR packet is received) as `esbInit()` is called before `bleEnabled` is set to 0. This PR fixes this difference.

Fix for Crazyswarm2 problem

---

docs/development/starting_development.md

Add missing bracket and replace deprecated "runToMain" with "runToEntryPoint".

Update starting_development.md to fix VSCode configuration

---

Makefile
src/esb.c
src/pm.c

Add functionality to nrf FW to be able to enable radiotest mode using compile flags.
Three different FWs can be built. Normal radiotest with chip antenna, radiotest using external antenna and 
recieve radiotest.

Add radiotest functionality to FW

---

src/platform.c

This PR adds the CFBL device type string to the firmware using the same string as for the STM32 OTP

Added the CFBL device type

---

src/ble/ble.c

When using BLE-only client, it is needed to differenciate multiple Crazyflies.
This PR adds the last 3 bytes of the random nRF51 address to the BLE device name. This allows client to easily differenciate multiple Crazyflies.

Add last 3 bytes of the MAC address to the ble name

---

Makefile
interface/crc32_calc.h
interface/memory.h
src/crc32_calc.c
src/main.c
src/memory.c

PR #69 introduced a 1-second delay before booting the STM32 and decks to prevent the GAP8 from freezing. However, we still saw the issue, even when using only the AI-deck. The severity varied depending on the combination of attached decks.
This PR increases the delay to 5 seconds, which, based on testing, significantly improves stability. However, if issues persist, a further increase may be necessary.
Additionally, this PR ensures that the delayed boot is deck-dependent. Now, the delay is only applied when an AI-deck is attached. To achieve this, we read the OW memory during startup. If no AI-deck is present, the previous 1-second delay is removed entirely.

Delay STM/decks boot by 5 seconds if AI-deck is attached

---

src/main.c

A short boot delay was initially introduced in commit 1f498f1bb73628dda2d72cc4ed6df32c53e50c21 to properly initialize the GAP8 on the AI-deck. In PR #102, the delay was removed when no AI-deck was detected to optimize boot time. However, it now appears that the system has started to rely on this delay, as removing it sometimes causes the radio to fail at startup. The exact reason remains unknown, but this commit restores the delay to maintain stability.

Reintroduce short boot delay to ensure radio startup reliability

---

src/uart.c

Corrects race condition where head pointer increment could cause buffer overflow in high-throughput UART scenarios. The issue occurred when head++ was used after bounds checking with nhead, potentially writing beyond the rxq buffer boundary.
Changes:
- Use pre-calculated nhead value consistently
- Replace head++ with head = nhead to prevent buffer corruption
- Maintains proper circular buffer semantics
Fixes potential data corruption and system instability in UART communication

Fix critical UART buffer overrun vulnerability in interrupt handler
